
# https://docs.microsoft.com/azure/devops/pipelines/languages/go
pool:
  vmImage: 'ubuntu-16.04'

variables:
  GOBIN:  '$(GOPATH)/bin' # Go binaries path
  GOROOT: '/usr/local/go1.11' # Go installation path
  GOPATH: '$(system.defaultWorkingDirectory)/gopath' # Go workspace path
  modulePath: '$(GOPATH)/src/terraform-provider-azuredevops' # Path to the module's code

name: 0.3$(Rev:.r)

steps:
- script: |
    mkdir -p '$(GOBIN)'
    mkdir -p '$(GOPATH)/pkg'
    mkdir -p '$(modulePath)'
    shopt -s extglob
    mv !(gopath) '$(modulePath)'
    echo '##vso[task.prependpath]$(GOBIN)'
    echo '##vso[task.prependpath]$(GOROOT)/bin'
    printenv
  displayName: 'Set up the Go workspace'
- task: Go@0
  displayName: 'go test'
  inputs:
    command: test
    arguments: '-v'
    workingDirectory: '$(modulePath)/azuredevops'
  env:
    AZURE_DEVOPS_TOKEN: "$(System.AccessToken)"
    AZURE_DEVOPS_ORGANIZATION: "mikaelkrief"
- task: Bash@3
  displayName: Install
  inputs:
    targetType: "filePath"
    filePath: $(modulePath)/scripts/build-provider.bash
    arguments: $(Build.BuildNumber) $(Build.BinariesDirectory)
    workingDirectory: '$(modulePath)'
- task: PublishBuildArtifacts@1
  displayName: 'Publish Artifact: drop'
  inputs:
    PathtoPublish: '$(Build.BinariesDirectory)'