
# https://docs.microsoft.com/azure/devops/pipelines/languages/go
pool:
  vmImage: 'ubuntu-16.04'

variables:
  GOBIN:  '$(GOPATH)/bin' # Go binaries path
  GOROOT: '/usr/local/go1.11' # Go installation path
  GOPATH: '$(system.defaultWorkingDirectory)/gopath' # Go workspace path
  modulePath: '$(GOPATH)/src/github.com/$(build.repository.name)' # Path to the module's code

name: 0.3$(Rev:.r)

steps:
- script: |
    mkdir -p '$(GOBIN)'
    mkdir -p '$(GOPATH)/pkg'
    mkdir -p '$(modulePath)'
    shopt -s extglob
    mv !(gopath) '$(modulePath)'
    echo '##vso[task.prependpath]$(GOBIN)'
    echo '##vso[task.prependpath]$(GOROOT)/bin'
    printenv
  displayName: 'Set up the Go workspace'
- task: Bash@3
  displayName: Install
  inputs:
    targetType: "filePath"
    filePath: $(modulePath)/scripts/buildgo.bash
    arguments: $(Build.BuildNumber) $(Build.BinariesDirectory)
    workingDirectory: '$(modulePath)'
- script: |
   cd $(modulePath)
   dir 
   cd $(Build.BinariesDirectory)
   dir
  displayName: 'Set up the Go workspace'
- task: GitHubRelease@0
  inputs:
    gitHubConnection: "GitHub connection 1"
    repositoryName: "mikaelkrief/terraform-provider-azuredevops"
    action: 'create' # Options: create, edit, delete
    target: '$(Build.SourceVersion)' # Required when action == Create || Action == Edit
    tagSource: 'auto' # Required when action == Create# Options: auto, manual
    tag: $(Build.BuildNumber) # Required when action == Edit || Action == Delete || TagSource == Manual
    title: $(Build.BuildNumber) # Optional
    #releaseNotesSource: 'file' # Optional. Options: file, input
    #releaseNotesFile: # Optional
    #releaseNotes: # Optional
    assets: '$(Build.BinariesDirectory)/*.zip' # Optional
    #assetUploadMode: 'delete' # Optional. Options: delete, replace
    #isDraft: false # Optional
    #isPreRelease: false # Optional
    #addChangeLog: true # Optional